Four-Talking/Nateam

- src/main/java/fourtalking/Nateam/cartgame/entity/CartGame.java
- src/main/java/fourtalking/Nateam/game/entity/Game.java
- src/main/java/fourtalking/Nateam/order/entity/Order.java
- src/main/java/fourtalking/Nateam/orderGame/entity/OrderGame.java
- src/main/java/fourtalking/Nateam/review/entity/Review.java
- src/main/java/fourtalking/Nateam/user/constant/UserRole.java
- src/main/java/fourtalking/Nateam/user/entity/User.java
> Design: 엔티티 설계 및 구현

- src/main/java/fourtalking/Nateam/review/entity/Review.java
Review 테이블에 userId가 빠져있어서 추가하였습니다.
> Fix: Review 테이블 userId 추가

- src/main/java/fourtalking/Nateam/game/controller/GameController.java
- src/main/java/fourtalking/Nateam/game/dto/GameGetDTO.java
- src/main/java/fourtalking/Nateam/game/service/GameService.java
추후에 해야할 일
1. userservice를 주입받아 userId를 이용해 userName 받아오기
2. reviewService를 주입받아 각 리뷰의 평점을 계산해 게임의 전체 평점 추출하는 로직 구현하기
> Feature: 게임 단건 조회 API 기능 구현

- src/main/java/fourtalking/Nateam/global/exception/common/ErrorCode.java
- src/main/java/fourtalking/Nateam/global/exception/review/ReviewNotFoundException.java
- src/main/java/fourtalking/Nateam/review/controller/ReviewController.java
- src/main/java/fourtalking/Nateam/review/dto/ReviewRegisterDTO.java
- src/main/java/fourtalking/Nateam/review/repository/ReviewRepository.java
- src/main/java/fourtalking/Nateam/review/service/ReviewService.java
gameId를 RequestParam으로 받고, 리뷰 내용과 별점은 Body로 받아서 
로그인한 사용자 ID를 읽은 후 리뷰 등록 하는 API 입니다.
> Feature: 리뷰 등록 API 기능 구현

- src/main/java/fourtalking/Nateam/game/controller/GameController.java
- src/main/java/fourtalking/Nateam/game/repositroy/GameRepository.java
- src/main/java/fourtalking/Nateam/game/service/GameService.java
최신순으로 게임 전체 목록 조회 API 구현, 추후에 페이징 적용
> Feature: 게임 전체 목록 조회 API 기능 구현

- src/main/java/fourtalking/Nateam/review/controller/ReviewController.java
- src/main/java/fourtalking/Nateam/review/dto/GetReviewDTO.java
- src/main/java/fourtalking/Nateam/review/dto/ReviewRegisterDTO.java
- src/main/java/fourtalking/Nateam/review/service/ReviewService.java
> Feature: 리뷰 단건 조회 기능 API 구현

- src/main/java/fourtalking/Nateam/cartgame/controller/CartGameController.java
- src/main/java/fourtalking/Nateam/cartgame/service/CartGameService.java
- src/main/java/fourtalking/Nateam/global/exception/cartGame/CartInGameNotFountException.java
- src/main/java/fourtalking/Nateam/global/exception/common/ErrorCode.java
- src/main/resources/application.yml
> feature:요청한 게임 장바구니 삭제

- src/main/java/fourtalking/Nateam/game/controller/GameController.java
- src/main/java/fourtalking/Nateam/game/dto/GameModifyDTO.java
- src/main/java/fourtalking/Nateam/game/entity/Game.java
- src/main/java/fourtalking/Nateam/game/service/GameService.java
게임의 이름, 게임 소개를 변경할 수 있는 게임 수정 API를 구현한다.
수정 요청한 사용자와 게임을 등록한 사용자가 같아야 지만 수정이 가능하고 아니라면 예외를 발생한다.
> Feature: 게임 수정 API 기능 구현

- src/main/java/fourtalking/Nateam/global/exception/common/ErrorCode.java
> Fix: ErrorCode 32라인 ; -> , 으로 변경

- src/main/java/fourtalking/Nateam/cartgame/controller/CartGameController.java
> refactor:카트 컨트롤러 수정

- src/main/java/fourtalking/Nateam/game/controller/GameController.java
- src/main/java/fourtalking/Nateam/game/service/GameService.java
삭제 요청한 사용자와 게임을 등록한 사용자가 같아야 지만 삭제가 가능하고 아니라면 예외를 발생한다.
> Feature: 게임 삭제 API 기능 구현

- src/main/java/fourtalking/Nateam/global/exception/common/ErrorCode.java
- src/main/java/fourtalking/Nateam/global/exception/user/DuplicatePasswordException.java
- src/main/java/fourtalking/Nateam/passwordhistory/entity/PasswordHistory.java
- src/main/java/fourtalking/Nateam/passwordhistory/repository/PasswordHistoryRepository.java
- src/main/java/fourtalking/Nateam/passwordhistory/service/PasswordHistoryService.java
- src/main/java/fourtalking/Nateam/user/controller/UserController.java
- src/main/java/fourtalking/Nateam/user/dto/ChangePasswordDTO.java
- src/main/java/fourtalking/Nateam/user/dto/SignupDTO.java
- src/main/java/fourtalking/Nateam/user/entity/User.java
- src/main/java/fourtalking/Nateam/user/service/UserService.java
> Feature: 비밀번호 변경 API 기능 구현

- src/main/java/fourtalking/Nateam/cartgame/repository/CartGameRepository.java
- src/main/java/fourtalking/Nateam/cartgame/service/CartGameService.java
장바구니 서비스-로그인중 장바구니 모두 삭제 메소드 추가
> feature:장바구니 모두 삭제 메소드 추가

- src/main/java/fourtalking/Nateam/order/service/OrderService.java
- src/main/java/fourtalking/Nateam/orderGame/service/OrderGameService.java
orderService수정,orderGameService 메소드 추가
> refactor:orderService수정,orderGameService 메소드 추가

- src/main/java/fourtalking/Nateam/order/service/OrderService.java
- src/main/java/fourtalking/Nateam/orderGame/orderGameRepository/OrderGameRepository.java
- src/main/java/fourtalking/Nateam/orderGame/service/OrderGameService.java
repository 참조 대신 orderGameService에서 기능을 받아오는걸로 수정했습니다.
> Fix: 주문 내역 삭제 기능 orderGameService로 위치 변경

- src/main/java/fourtalking/Nateam/review/service/ReviewService.java
> Fix: 게임이 없을 때 리뷰가 등록되는 버그수정

- src/main/java/fourtalking/Nateam/user/entity/User.java
> Fix: User 테이블 이름을 Users로 변경

- src/main/java/fourtalking/Nateam/review/service/ReviewService.java
- src/test/java/fourtalking/Nateam/review/service/ReviewServiceTest.java
- src/test/java/fourtalking/Nateam/test/CommonTest.java
> Feature: review 등록 테스트 API 구현

- src/test/java/fourtalking/Nateam/review/service/ReviewServiceTest.java
> Feature: 리뷰 조회 Test 기능 API 개발

- src/test/java/fourtalking/Nateam/review/service/ReviewServiceTest.java
> Feature: 리뷰 전체 조회 서비스 테스트

- src/test/java/fourtalking/Nateam/review/service/ReviewServiceTest.java
> Feature: 리뷰 삭제 서비스 테스트

- src/main/java/fourtalking/Nateam/game/repositroy/GameRepository.java
- src/main/java/fourtalking/Nateam/game/service/GameService.java
GameService에서 ReviewService에 대한 종속성 제거
ReviewService를 통해 가져오던 게임 평점을 GameRepository.getGameReviewRank를 통해 가져오는 것으로 변경
> Fix: GameService와 ReviewService의 순환참조 해결

- src/main/java/fourtalking/Nateam/order/controller/OrderController.java
- src/main/java/fourtalking/Nateam/order/dto/OrderGameDTO.java
- src/main/java/fourtalking/Nateam/order/dto/OrderGameGetAllDTO.java
- src/main/java/fourtalking/Nateam/order/dto/OrderGetDTO.java
- src/main/java/fourtalking/Nateam/order/repository/OrderRepository.java
- src/main/java/fourtalking/Nateam/order/service/OrderService.java
> feature:주문 전체 목록 조회 기능

- src/main/java/fourtalking/Nateam/global/exception/common/ErrorCode.java
- src/main/java/fourtalking/Nateam/global/exception/order/OrderEmptyCartException.java
- src/main/java/fourtalking/Nateam/order/controller/OrderController.java
- src/main/java/fourtalking/Nateam/order/dto/OrderGameDTO.java
- src/main/java/fourtalking/Nateam/order/dto/OrderGameGetAllDTO.java
- src/main/java/fourtalking/Nateam/order/dto/OrderGetDTO.java
- src/main/java/fourtalking/Nateam/order/repository/OrderRepository.java
- src/main/java/fourtalking/Nateam/order/service/OrderService.java
> Refactor: 주문하기 예외 추가

- src/test/java/fourtalking/Nateam/cartgame/service/CartGameServiceTest.java
> Test : 장바구니 수정,조회,삭제 테스트

- src/test/java/fourtalking/Nateam/cartgame/service/CartGameServiceTest.java
- src/test/java/fourtalking/Nateam/orders/service/OrderserviceTest.java
- src/test/java/fourtalking/Nateam/test/CommonTest.java
> Test: 주문 추가,단일조회,전체조회,삭제 테스트
